In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib

Using matplotlib backend: Qt5Agg


# set options to display all rows and columns

In [2]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

# Read the data

In [2]:
bank_sub=pd.read_csv('D:/Machine learning data set/Banking subscription/Banking subscription/bank-additional-full.csv',sep=';')
bank_sub.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

###Remove unnecessary columns

In [3]:
bank_sub1=bank_sub.drop(['education','marital','contact','month','day_of_week','campaign','nr.employed'],axis=1)

In [4]:
len(bank_sub1)

41188

In [4]:
bank_sub1.pdays.unique()

array([999,   6,   4,   3,   5,   1,   0,  10,   7,   8,   9,  11,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27,
        20], dtype=int64)

In [5]:
bank_sub1['pdays']=bank_sub1['pdays'].apply(lambda x : -1 if x == 999 else x)
bank_sub1.head()

age        job  default housing loan  duration  pdays  previous  \
0   56  housemaid       no      no   no       261     -1         0   
1   57   services  unknown      no   no       149     -1         0   
2   37   services       no     yes   no       226     -1         0   
3   40     admin.       no      no   no       151     -1         0   
4   56   services       no      no  yes       307     -1         0   

      poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m   y  
0  nonexistent           1.1          93.994          -36.4      4.857  no  
1  nonexistent           1.1          93.994          -36.4      4.857  no  
2  nonexistent           1.1          93.994          -36.4      4.857  no  
3  nonexistent           1.1          93.994          -36.4      4.857  no  
4  nonexistent           1.1          93.994          -36.4      4.857  no

# handing categorical features

In [6]:
bank_sub1=pd.get_dummies(bank_sub1,columns=['loan','default','housing','poutcome','y'],drop_first=True)
bank_sub1.head()

age        job  duration  pdays  previous  emp.var.rate  cons.price.idx  \
0   56  housemaid       261     -1         0           1.1          93.994   
1   57   services       149     -1         0           1.1          93.994   
2   37   services       226     -1         0           1.1          93.994   
3   40     admin.       151     -1         0           1.1          93.994   
4   56   services       307     -1         0           1.1          93.994   

   cons.conf.idx  euribor3m  loan_unknown  loan_yes  default_unknown  \
0          -36.4      4.857             0         0                0   
1          -36.4      4.857             0         0                1   
2          -36.4      4.857             0         0                0   
3          -36.4      4.857             0         0                0   
4          -36.4      4.857             0         1                0   

   default_yes  housing_unknown  housing_yes  poutcome_nonexistent  \
0            0                0            0                     1   
1            0                0            0                     1   
2            0                0            1                     1   
3            0                0            0                     1   
4            0                0            0                     1   

   poutcome_success  y_yes  
0                 0      0  
1                 0      0  
2                 0      0  
3                 0      0  
4                 0      0

In [113]:
def pred_y_n(x):
    y={'yes':1,'no':0}
    return y[x]
bank_sub1['y']=bank_sub1['y'].apply(pred_y_n)
bank_sub1.head()

KeyError: 0

## checking the imbalance of dataset

In [7]:
bank_sub1.rename(columns={'y_yes':'y'},inplace=True)
bank_sub1.columns

Index(['age', 'job', 'duration', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'loan_unknown',
       'loan_yes', 'default_unknown', 'default_yes', 'housing_unknown',
       'housing_yes', 'poutcome_nonexistent', 'poutcome_success', 'y'],
      dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
bank_sub1['job']=le.fit_transform(bank_sub1['job'])
bank_sub1.head()

age  job  duration  pdays  previous  emp.var.rate  cons.price.idx  \
0   56    3       261     -1         0           1.1          93.994   
1   57    7       149     -1         0           1.1          93.994   
2   37    7       226     -1         0           1.1          93.994   
3   40    0       151     -1         0           1.1          93.994   
4   56    7       307     -1         0           1.1          93.994   

   cons.conf.idx  euribor3m  loan_unknown  loan_yes  default_unknown  \
0          -36.4      4.857             0         0                0   
1          -36.4      4.857             0         0                1   
2          -36.4      4.857             0         0                0   
3          -36.4      4.857             0         0                0   
4          -36.4      4.857             0         1                0   

   default_yes  housing_unknown  housing_yes  poutcome_nonexistent  \
0            0                0            0                     1   
1            0                0            0                     1   
2            0                0            1                     1   
3            0                0            0                     1   
4            0                0            0                     1   

   poutcome_success  y  
0                 0  0  
1                 0  0  
2                 0  0  
3                 0  0  
4                 0  0

# finding the correlation between features & target variable

In [125]:
bank_sub1.corr()['y'].abs().sort_values()

loan_unknown            0.002270
housing_unknown         0.002270
default_yes             0.003041
loan_yes                0.004466
housing_yes             0.011743
job                     0.025122
age                     0.030399
cons.conf.idx           0.054878
default_unknown         0.099293
cons.price.idx          0.136211
poutcome_nonexistent    0.193507
previous                0.230181
pdays                   0.279025
emp.var.rate            0.298334
euribor3m               0.307771
poutcome_success        0.316269
duration                0.405274
y                       1.000000
Name: y, dtype: float64

## handling imbalance dataset

In [9]:
x=bank_sub1[[col for col in bank_sub1.columns if col not in 'y']]
y=bank_sub1['y']
x.columns

Index(['age', 'job', 'duration', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'loan_unknown',
       'loan_yes', 'default_unknown', 'default_yes', 'housing_unknown',
       'housing_yes', 'poutcome_nonexistent', 'poutcome_success'],
      dtype='object')

In [10]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [11]:
os=RandomOverSampler(sampling_strategy=0.9)
#us=RandomUnderSampler()
X,Y=os.fit_sample(x,y)

In [12]:
X.shape
X.shape,Y.shape

((69441, 17), (69441,))

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score,train_test_split,RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

In [134]:
X[X.duplicated() == True].index
bank_sub1[bank_sub1.index[882]

SyntaxError: invalid syntax (<ipython-input-134-c53e7298c9c7>, line 2)

In [41]:
n_est=np.arange(100,1000,100)
max_depth=[int(x) for x in np.arange(5,20)]
min_samples_split = [2,4,6]
min_samples_leaf = [1, 2, 4]
random_grid = {'n_estimators': n_est,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

In [42]:
rand=RandomizedSearchCV(RFC,param_distributions=random_grid,cv=5,n_jobs=-1)
rand.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_estimators=200),
                   n_jobs=-1,
                   param_distributions={'max_depth': [5, 6, 7, 8, 9, 10, 11, 12,
                                                      13, 14, 15, 16, 17, 18,
                                                      19],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 4, 6],
                                        'n_estimators': array([100, 200, 300, 400, 500, 600, 700, 800, 900])})

In [ ]:
#n_estimators--number of decison tree will be used


In [45]:
rand.best_estimator_

RandomForestClassifier(max_depth=6, min_samples_leaf=4, min_samples_split=4,
                       n_estimators=200)

In [14]:
#DT=DecisionTreeClassifier(criterion='gini')
#RFC=RandomForestClassifier(max_depth=6, min_samples_leaf=4, min_samples_split=4,n_estimators=200)
RFC=RandomForestClassifier(n_estimators=200)
cv=cross_val_score(RFC,X,Y,scoring='accuracy',cv=10)
cv

array([0.97609791, 0.97883065, 0.93476382, 0.96990207, 0.96442972,
       0.95017281, 0.77923387, 0.5843894 , 0.85210253, 0.57315668])

In [79]:
#X.drop(X.iloc[46001:46003].index,axis=0,inplace=True)

In [15]:
cv.mean()

0.8563079478987303

In [117]:
X.shape,Y.shape

((73096, 17), (73096,))

In [16]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=124)
#DT.fit(x_train,y_train)
RFC.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [19]:
accuracy_score(y_test,RFC.predict(x_test))
confusion_matrix(y_test,RFC.predict(x_test))
#f1_score(y_test,RFC.predict(x_test))

array([[6855,  470],
       [   9, 6555]], dtype=int64)

In [20]:
import pickle

In [28]:
pickle.dump(RFC,open('Rfc.pkl','wb'))
rfc=pickle.load(open('Rfc.pkl','rb'))


AttributeError: 'RandomForestClassifier' object has no attribute 'close'